---
# Decide in che mondi il plugin è attivo.
# Esempio: ["NomeMondo1,"NomeMondo2"]
# Utilizza worlds: "all" se vuoi attivarle su tutti i mondi
# Decides in which worlds the plugin is active.
# Example ["WorldName1,"WorldName2"]
# use "all" if you want to activate them in every world
worlds: ["World1","World2"]

# Imposta quanti cuori da ogni zuppa (in decimi)
# esempio: per dare 4 cuori e mezzo utilizza il valore 4.5
# Set how many hearts from each soup (in tenths)
# example: to give 4 hearts and a half hearts use the value 4.5
heart: 2.5
---